/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTopPagesRouteImport } from './routes/_authenticated/app.top-pages'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSeoAuditRouteImport } from './routes/_authenticated/app.seo-audit'
import { Route as AuthenticatedAppProspectCampaignsRouteImport } from './routes/_authenticated/app.prospect-campaigns'
import { Route as AuthenticatedAppPipelineRouteImport } from './routes/_authenticated/app.pipeline'
import { Route as AuthenticatedAppOpportunityScoresRouteImport } from './routes/_authenticated/app.opportunity-scores'
import { Route as AuthenticatedAppListsRouteImport } from './routes/_authenticated/app.lists'
import { Route as AuthenticatedAppFindLeadsRouteImport } from './routes/_authenticated/app.find-leads'
import { Route as AuthenticatedAppBulkScanRouteImport } from './routes/_authenticated/app.bulk-scan'
import { Route as AuthenticatedAppAuditSitesRouteImport } from './routes/_authenticated/app.audit-sites'
import { Route as AuthenticatedAppAssistantRouteImport } from './routes/_authenticated/app.assistant'
import { Route as AuthenticatedAppAssistantThreadIdRouteImport } from './routes/_authenticated/app.assistant.$threadId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTopPagesRoute =
  AuthenticatedAppTopPagesRouteImport.update({
    id: '/app/top-pages',
    path: '/app/top-pages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSeoAuditRoute =
  AuthenticatedAppSeoAuditRouteImport.update({
    id: '/app/seo-audit',
    path: '/app/seo-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProspectCampaignsRoute =
  AuthenticatedAppProspectCampaignsRouteImport.update({
    id: '/app/prospect-campaigns',
    path: '/app/prospect-campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPipelineRoute =
  AuthenticatedAppPipelineRouteImport.update({
    id: '/app/pipeline',
    path: '/app/pipeline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppOpportunityScoresRoute =
  AuthenticatedAppOpportunityScoresRouteImport.update({
    id: '/app/opportunity-scores',
    path: '/app/opportunity-scores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppListsRoute = AuthenticatedAppListsRouteImport.update({
  id: '/app/lists',
  path: '/app/lists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppFindLeadsRoute =
  AuthenticatedAppFindLeadsRouteImport.update({
    id: '/app/find-leads',
    path: '/app/find-leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBulkScanRoute =
  AuthenticatedAppBulkScanRouteImport.update({
    id: '/app/bulk-scan',
    path: '/app/bulk-scan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAuditSitesRoute =
  AuthenticatedAppAuditSitesRouteImport.update({
    id: '/app/audit-sites',
    path: '/app/audit-sites',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAssistantRoute =
  AuthenticatedAppAssistantRouteImport.update({
    id: '/app/assistant',
    path: '/app/assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAssistantThreadIdRoute =
  AuthenticatedAppAssistantThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedAppAssistantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRouteWithChildren
  '/app/audit-sites': typeof AuthenticatedAppAuditSitesRoute
  '/app/bulk-scan': typeof AuthenticatedAppBulkScanRoute
  '/app/find-leads': typeof AuthenticatedAppFindLeadsRoute
  '/app/lists': typeof AuthenticatedAppListsRoute
  '/app/opportunity-scores': typeof AuthenticatedAppOpportunityScoresRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/prospect-campaigns': typeof AuthenticatedAppProspectCampaignsRoute
  '/app/seo-audit': typeof AuthenticatedAppSeoAuditRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/top-pages': typeof AuthenticatedAppTopPagesRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/assistant/$threadId': typeof AuthenticatedAppAssistantThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/app/assistant': typeof AuthenticatedAppAssistantRouteWithChildren
  '/app/audit-sites': typeof AuthenticatedAppAuditSitesRoute
  '/app/bulk-scan': typeof AuthenticatedAppBulkScanRoute
  '/app/find-leads': typeof AuthenticatedAppFindLeadsRoute
  '/app/lists': typeof AuthenticatedAppListsRoute
  '/app/opportunity-scores': typeof AuthenticatedAppOpportunityScoresRoute
  '/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/app/prospect-campaigns': typeof AuthenticatedAppProspectCampaignsRoute
  '/app/seo-audit': typeof AuthenticatedAppSeoAuditRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/top-pages': typeof AuthenticatedAppTopPagesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/assistant/$threadId': typeof AuthenticatedAppAssistantThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/app/assistant': typeof AuthenticatedAppAssistantRouteWithChildren
  '/_authenticated/app/audit-sites': typeof AuthenticatedAppAuditSitesRoute
  '/_authenticated/app/bulk-scan': typeof AuthenticatedAppBulkScanRoute
  '/_authenticated/app/find-leads': typeof AuthenticatedAppFindLeadsRoute
  '/_authenticated/app/lists': typeof AuthenticatedAppListsRoute
  '/_authenticated/app/opportunity-scores': typeof AuthenticatedAppOpportunityScoresRoute
  '/_authenticated/app/pipeline': typeof AuthenticatedAppPipelineRoute
  '/_authenticated/app/prospect-campaigns': typeof AuthenticatedAppProspectCampaignsRoute
  '/_authenticated/app/seo-audit': typeof AuthenticatedAppSeoAuditRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/top-pages': typeof AuthenticatedAppTopPagesRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/assistant/$threadId': typeof AuthenticatedAppAssistantThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/app/assistant'
    | '/app/audit-sites'
    | '/app/bulk-scan'
    | '/app/find-leads'
    | '/app/lists'
    | '/app/opportunity-scores'
    | '/app/pipeline'
    | '/app/prospect-campaigns'
    | '/app/seo-audit'
    | '/app/settings'
    | '/app/top-pages'
    | '/app/'
    | '/app/assistant/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/app/assistant'
    | '/app/audit-sites'
    | '/app/bulk-scan'
    | '/app/find-leads'
    | '/app/lists'
    | '/app/opportunity-scores'
    | '/app/pipeline'
    | '/app/prospect-campaigns'
    | '/app/seo-audit'
    | '/app/settings'
    | '/app/top-pages'
    | '/app'
    | '/app/assistant/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/api/chat'
    | '/_authenticated/app/assistant'
    | '/_authenticated/app/audit-sites'
    | '/_authenticated/app/bulk-scan'
    | '/_authenticated/app/find-leads'
    | '/_authenticated/app/lists'
    | '/_authenticated/app/opportunity-scores'
    | '/_authenticated/app/pipeline'
    | '/_authenticated/app/prospect-campaigns'
    | '/_authenticated/app/seo-audit'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/top-pages'
    | '/_authenticated/app/'
    | '/_authenticated/app/assistant/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/top-pages': {
      id: '/_authenticated/app/top-pages'
      path: '/app/top-pages'
      fullPath: '/app/top-pages'
      preLoaderRoute: typeof AuthenticatedAppTopPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/seo-audit': {
      id: '/_authenticated/app/seo-audit'
      path: '/app/seo-audit'
      fullPath: '/app/seo-audit'
      preLoaderRoute: typeof AuthenticatedAppSeoAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/prospect-campaigns': {
      id: '/_authenticated/app/prospect-campaigns'
      path: '/app/prospect-campaigns'
      fullPath: '/app/prospect-campaigns'
      preLoaderRoute: typeof AuthenticatedAppProspectCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pipeline': {
      id: '/_authenticated/app/pipeline'
      path: '/app/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AuthenticatedAppPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/opportunity-scores': {
      id: '/_authenticated/app/opportunity-scores'
      path: '/app/opportunity-scores'
      fullPath: '/app/opportunity-scores'
      preLoaderRoute: typeof AuthenticatedAppOpportunityScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/lists': {
      id: '/_authenticated/app/lists'
      path: '/app/lists'
      fullPath: '/app/lists'
      preLoaderRoute: typeof AuthenticatedAppListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/find-leads': {
      id: '/_authenticated/app/find-leads'
      path: '/app/find-leads'
      fullPath: '/app/find-leads'
      preLoaderRoute: typeof AuthenticatedAppFindLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bulk-scan': {
      id: '/_authenticated/app/bulk-scan'
      path: '/app/bulk-scan'
      fullPath: '/app/bulk-scan'
      preLoaderRoute: typeof AuthenticatedAppBulkScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/audit-sites': {
      id: '/_authenticated/app/audit-sites'
      path: '/app/audit-sites'
      fullPath: '/app/audit-sites'
      preLoaderRoute: typeof AuthenticatedAppAuditSitesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assistant': {
      id: '/_authenticated/app/assistant'
      path: '/app/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AuthenticatedAppAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assistant/$threadId': {
      id: '/_authenticated/app/assistant/$threadId'
      path: '/$threadId'
      fullPath: '/app/assistant/$threadId'
      preLoaderRoute: typeof AuthenticatedAppAssistantThreadIdRouteImport
      parentRoute: typeof AuthenticatedAppAssistantRoute
    }
  }
}

interface AuthenticatedAppAssistantRouteChildren {
  AuthenticatedAppAssistantThreadIdRoute: typeof AuthenticatedAppAssistantThreadIdRoute
}

const AuthenticatedAppAssistantRouteChildren: AuthenticatedAppAssistantRouteChildren =
  {
    AuthenticatedAppAssistantThreadIdRoute:
      AuthenticatedAppAssistantThreadIdRoute,
  }

const AuthenticatedAppAssistantRouteWithChildren =
  AuthenticatedAppAssistantRoute._addFileChildren(
    AuthenticatedAppAssistantRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAssistantRoute: typeof AuthenticatedAppAssistantRouteWithChildren
  AuthenticatedAppAuditSitesRoute: typeof AuthenticatedAppAuditSitesRoute
  AuthenticatedAppBulkScanRoute: typeof AuthenticatedAppBulkScanRoute
  AuthenticatedAppFindLeadsRoute: typeof AuthenticatedAppFindLeadsRoute
  AuthenticatedAppListsRoute: typeof AuthenticatedAppListsRoute
  AuthenticatedAppOpportunityScoresRoute: typeof AuthenticatedAppOpportunityScoresRoute
  AuthenticatedAppPipelineRoute: typeof AuthenticatedAppPipelineRoute
  AuthenticatedAppProspectCampaignsRoute: typeof AuthenticatedAppProspectCampaignsRoute
  AuthenticatedAppSeoAuditRoute: typeof AuthenticatedAppSeoAuditRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTopPagesRoute: typeof AuthenticatedAppTopPagesRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAssistantRoute: AuthenticatedAppAssistantRouteWithChildren,
  AuthenticatedAppAuditSitesRoute: AuthenticatedAppAuditSitesRoute,
  AuthenticatedAppBulkScanRoute: AuthenticatedAppBulkScanRoute,
  AuthenticatedAppFindLeadsRoute: AuthenticatedAppFindLeadsRoute,
  AuthenticatedAppListsRoute: AuthenticatedAppListsRoute,
  AuthenticatedAppOpportunityScoresRoute:
    AuthenticatedAppOpportunityScoresRoute,
  AuthenticatedAppPipelineRoute: AuthenticatedAppPipelineRoute,
  AuthenticatedAppProspectCampaignsRoute:
    AuthenticatedAppProspectCampaignsRoute,
  AuthenticatedAppSeoAuditRoute: AuthenticatedAppSeoAuditRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTopPagesRoute: AuthenticatedAppTopPagesRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
